include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/firebase_options.dart"

  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
    deprecated_member_use: warning
    unused_import: error
    unused_local_variable: error

linter:
  rules:
    # Disable rules that conflict with code generation
    public_member_api_docs: false
    one_member_abstracts: false

    # Enable stricter rules
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_pub_dependencies: true
